# -*- coding: utf-8 -*-
"""NBA_Data_Analysis_Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ieHkvKSqAvy6_-5tlm4BO7ZWnxCdd5u-
"""

import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_excel('/content/NBA Project.xlsx')
print(df.shape)
df.head()

# Keeping the important columns.
columns_to_keep = ['Year', 'Player', 'Pos', 'G', 'MP', 'FGA', '3PA', '3P', 'PTS']
df = df[columns_to_keep].copy()

# types of data
print(df.dtypes)

print(df.isnull().sum())
#how much is null?
df = df.dropna(subset=['3PA'])
#fill the empthy cells with 0
df = df.fillna(0)

print("\nMissing values after cleaning:", df.isnull().sum().sum())

# Cleaning the Data. Players who Played more then 10 games and more then 100 minutes
df = df[(df['G'] >= 10) & (df['MP'] >= 100)]
# make sure the showen data is between 1997-2017
df = df[df['Year'] >= 1997]
df.head()

# Initial Cleaning for 1997-2017 and Trade Duplicates
df_all = df[(df['Year'] >= 1997) & (df['Year'] <= 2017)].copy()
df_all = df_all.drop_duplicates(subset=['Player', 'Year'], keep='first')

# Calculate the mean for all players
yearly_vol_all = df_all.groupby('Year')['3PA'].mean()

# Visualization
plt.figure(figsize=(12, 6))
plt.plot(yearly_vol_all.index, yearly_vol_all.values, marker='o', color='royalblue', linewidth=2.5, label='Avg 3PA (All Players)')

plt.title('NBA Evolution: Average 3-Point Attempts - All Players (1997-2017)', fontsize=15, fontweight='bold')
plt.xlabel('Year', fontsize=12)
plt.ylabel('Average 3PA per Player', fontsize=12)
plt.xlim(1997, 2017)
plt.xticks(range(1997, 2018, 2))
plt.grid(True, linestyle='--', alpha=0.6)
plt.legend(loc='upper left', shadow=True)
plt.show()
plt.savefig('nba_revolution_plot.png', dpi=300)

# 1. Filter for the years 1997-2017 and remove trade duplicates
df_acc = df[(df['Year'] >= 1997) & (df['Year'] <= 2017)].copy()
df_acc = df_acc.drop_duplicates(subset=['Player', 'Year'], keep='first')

# 2. Calculate Shooting Percentage for ALL players
# We use fillna(0) because players with 0 attempts would result in 'NaN'
df_acc['3P_Pct'] = df_acc['3P'] / df_acc['3PA']
df_acc['3P_Pct'] = df_acc['3P_Pct'].fillna(0)

# 3. Calculate the mean accuracy for the whole league
yearly_accuracy = df_acc.groupby('Year')['3P_Pct'].mean()

# 4. Visualization
plt.figure(figsize=(12, 6))
plt.plot(yearly_accuracy.index, yearly_accuracy.values,
         marker='s', color='forestgreen', linewidth=2.5, label='Avg 3P Accuracy (League Wide)')

# 5. Styling in English
plt.title('NBA Evolution: Average 3-Point Accuracy - All Players (1997-2017)', fontsize=15, fontweight='bold')
plt.xlabel('Year', fontsize=12)
plt.ylabel('3-Point Percentage (3P%)', fontsize=12)

# Legend and Axis formatting
plt.legend(loc='upper left', shadow=True)
plt.xlim(1997, 2017)
plt.xticks(range(1997, 2018, 2))

# Important: We adjust the Y-limit to show the lower accuracy of the entire league
plt.ylim(0.20, 0.35)
plt.grid(True, linestyle='--', alpha=0.6)

plt.show()
plt.savefig('nba_revolution_plot.png', dpi=300)

# 1. Prepare Data - 1997-2017, Clean Trades
df_final = df[(df['Year'] >= 1997) & (df['Year'] <= 2017)].copy()
df_final = df_final.drop_duplicates(subset=['Player', 'Year'], keep='first')

# 2. Calculate Pct for ALL players (handling division by zero)
df_final['3P_Pct'] = df_final['3P'] / df_final['3PA']
df_final['3P_Pct'] = df_final['3P_Pct'].fillna(0) # Fill 0 for players with no attempts

# 3. Aggregate - MEAN for ALL players
# This will match your first graph where 2017 is around 140
combined_all = df_final.groupby('Year').agg({
    '3PA': 'mean',
    '3P_Pct': 'mean'
})

# 4. Create Visualization
fig, ax1 = plt.subplots(figsize=(14, 8))

# Primary Axis: Volume (Bars) - Now showing the 140 avg
ax1.bar(combined_all.index, combined_all['3PA'], color='skyblue', alpha=0.4, label='Avg 3PA (All League)')
ax1.set_xlabel('Season (Year)', fontsize=12, fontweight='bold')
ax1.set_ylabel('Average Attempts (League Wide)', color='navy', fontsize=12, fontweight='bold')
ax1.tick_params(axis='y', labelcolor='navy')

# Secondary Axis: Accuracy (Line)
ax2 = ax1.twinx()
ax2.plot(combined_all.index, combined_all['3P_Pct'], color='crimson', marker='o', linewidth=3, label='Avg 3P Accuracy %')
ax2.set_ylabel('Average Accuracy %', color='crimson', fontsize=12, fontweight='bold')
ax2.tick_params(axis='y', labelcolor='crimson')

# Set specific limits to make the graph clear
ax2.set_ylim(0.20, 0.40) # Accuracy for the WHOLE league is lower (around 25-30%)
plt.xlim(1996.5, 2017.5)
plt.xticks(range(1997, 2018, 2))

plt.title('NBA 3-Point Revolution: League-Wide Trends (1997-2017)', fontsize=18, fontweight='bold')
ax1.grid(axis='y', linestyle='--', alpha=0.3)

# Legend
lines1, labels1 = ax1.get_legend_handles_labels()
lines2, labels2 = ax2.get_legend_handles_labels()
ax2.legend(lines1 + lines2, labels1 + labels2, loc='upper left', shadow=True)

plt.show()
plt.savefig('nba_revolution_plot.png', dpi=300)

# 1. Re-defining the clean data for positions
df_pos_acc = df[(df['Year'] >= 1997) & (df['Year'] <= 2017)].copy()
df_pos_acc = df_pos_acc.drop_duplicates(subset=['Player', 'Year'], keep='first')

# 2. Clean positions (
df_pos_acc['Pos_Clean'] = df_pos_acc['Pos'].str.split('-').str[0]

# 3. Calculate 3P% and handle missing values
df_pos_acc['3P_Pct'] = df_pos_acc['3P'] / df_pos_acc['3PA']
df_pos_acc['3P_Pct'] = df_pos_acc['3P_Pct'].fillna(0)

# 4. Filter specifically for 1997, 2007, and 2017 to show the evolution
years_to_show = [1997, 2007, 2017]
df_comparison = df_pos_acc[df_pos_acc['Year'].isin(years_to_show)]

# 5. Create the Pivot Table for the Bar Chart
# Rows: Positions, Columns: Selected Years
pos_bar_data = df_comparison.pivot_table(index='Pos_Clean', columns='Year', values='3P_Pct', aggfunc='mean')

# Reorder to traditional NBA positions
traditional_order = ['PG', 'SG', 'SF', 'PF', 'C']
pos_bar_data = pos_bar_data.reindex(traditional_order)

# 6. Visualization - Grouped Bar Chart
pos_bar_data.plot(kind='bar', figsize=(12, 7), color=['#A9CCE3', '#5499C7', '#154360'], edgecolor='black')

# Styling
plt.title('NBA Evolution: 3P% Accuracy by Position (1997 vs 2007 vs 2017)', fontsize=16, fontweight='bold')
plt.ylabel('Average Shooting Percentage (3P%)', fontsize=12)
plt.xlabel('Position', fontsize=12)
plt.xticks(rotation=0) # Keeps position names horizontal
plt.legend(title='Season', shadow=True)
plt.grid(axis='y', linestyle='--', alpha=0.4)

plt.show()
plt.savefig('nba_revolution_plot.png', dpi=300)

# 1. Filter data for the last 20 years and remove duplicates
df_players = df[(df['Year'] >= 1997) & (df['Year'] <= 2017)].copy()
df_players = df_players.drop_duplicates(subset=['Player', 'Year'], keep='first')

# 2. Group by Player to sum their total 3P and 3PA over the entire period
career_stats = df_players.groupby('Player').agg({
    '3P': 'sum',
    '3PA': 'sum'
})

# 3. Calculate career 3P% for this period
career_stats['3P_Pct'] = career_stats['3P'] / career_stats['3PA']

  # 4. Set a minimum threshold to ensure they are consistent shooters
  # (e.g., at least 500 attempts over 20 years)
  min_attempts = 500
  top_shooters = career_stats[career_stats['3PA'] >= min_attempts].copy()

  # 5. Sort by percentage and take the top 10
  top_10_shooters = top_shooters.sort_values(by='3P_Pct', ascending=False).head(10)

# Display the results
print(f"Top 10 3-Point Shooters (1997-2017) with at least {min_attempts} attempts:")
print(top_10_shooters[['3PA', '3P_Pct']])

# 1. Preparation: Sort the data
top_10_plot = top_10_shooters.sort_values(by='3P_Pct', ascending=True) # Ascending for horizontal bar

# 2. Visualization
plt.figure(figsize=(12, 8))
bars = plt.barh(top_10_plot.index, top_10_plot['3P_Pct'], color='skyblue', edgecolor='navy')

# 3. Styling
plt.title('Top 10 NBA 3-Point Shooters: Career Accuracy (1997-2017)', fontsize=16, fontweight='bold', pad=20)
plt.xlabel('3-Point Percentage (3P%)', fontsize=12)
plt.xlim(0.40, 0.45) # Zoom in to see the small differences between legends
plt.grid(axis='x', linestyle='--', alpha=0.6)

# 4. Adding labels to the bars (The exact percentage)
for bar in bars:
    width = bar.get_width()
    plt.text(width + 0.001, bar.get_y() + bar.get_height()/2,
             f'{width:.2%}', va='center', fontsize=10, fontweight='bold')

plt.tight_layout()
plt.show()
plt.savefig('nba_revolution_plot.png', dpi=300)